### PR TITLE
Add link link to Exercism in documentation

### PR DESCRIPTION
**Pull request by human154**

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
This isn't documentation so I don't think this is the right place to put this. Or at least not in the first main section there.

Perhaps we could have another section lower for external content and courses?

**Comment by human154** [comment]
...again, my goal is just to make the exorcism content a bit more discoverable. i.e. more so than hoping people will find it many lines down on the "awesome gleam" list.  This way all that community learning content is linked to directly and becomes more discoverable.

**Comment by human154** [comment]
How does that look?

**Review by lpil — APPROVED** [review]
Thank you

**Pull request merged**
