### PR TITLE
Add Getting Started link on index

### PR DESCRIPTION
**Pull request by rockerBOO**
My initial goal was I already knew about gleam but I need to get it installed. The path was `docs -> getting started` so this adds it on the homepage.

Screenshot_2020-11-30 Gleam

### CODE REVIEW

**Comment by lpil** [comment]
How about as a button below the text in the hero section at the pink top? I think that would be more visually appealling and more prominent.

**Comment by rockerBOO** [comment]
Screenshot_2020-11-30 Gleam(1)

**Comment by lpil** [comment]
I don't think the default button styling fits with the Gleam branding. Perhaps a white button with a rounded left and right side?

**Comment by rockerBOO** [comment]
I am not sure what you mean in terms of changing how it looks? I would say its a white button that's rounded currently. It matches the sponsor button on the top right. 

I am cool with whatever the changes just not sure what to change.

**Comment by lpil** [comment]
Probably easier to have a go myself than to badly explain what I mean! I don't wanna waste your time :)

Thank you!

**Comment by rockerBOO** [comment]
Ohhh I just looked and I see the problem. 

I thought I moved it from the browser properly but I must of did something wrong. 

I was editing it in the browser. 

Sorry for the confusion :).

**Comment by lpil** [comment]
No worries at all! :)

**Pull request merged**
