### PR TITLE
Add scoop to install options

### PR DESCRIPTION
**Pull request by foresterre**

### CODE REVIEW

**Comment by lpil** [comment]
Thank you!

It looks like Scoop doesn't have the most recent version of Gleam. What's the process for upgrading it? Chocolatey's being out of date caused us some issues and confusion so I'd like recommended repositories to be up-to-date.

**Comment by foresterre** [comment]
Well that's odd, I see `0.28.3` as the latest version in the main (default) bucket.

2023_05_13_gleam

**Comment by lpil** [comment]
Oh fab! I guess the website I was looking at was wrong. I don't know Scoop 😁

**Review by lpil — APPROVED** [review]
💜

**Pull request merged**
