### PR TITLE
Add a bunch of Lucys

### PR DESCRIPTION
**Pull request by okkdev**
Adds the Lucys which are already available as Discord emojis, as well as a "tiny" lucy optimized for small use cases.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Could you remove those other than the tiny ones please. 🙏 

What do they look like when rendered on the web page? Are they suitably small?

**Comment by okkdev** [comment]
Oh sure, should I add the other ones in a separate PR or not at all?

Right now all of them have the same size, should I display the tiny ones small?

**Comment by lpil** [comment]
Not added, they don't match the Gleam branding or tone so they're not suited to be added to the official assets.

Yes please, the tiny ones should be shown at the size at which they should be used.

**Comment by okkdev** [comment]
Oh my bad! I was asked to PR them after they got added on the Discord, I just didn't get around to doing it till now.

Sure, they'll be very tiny and easy to miss as 16x16px tho!

**Comment by okkdev** [comment]
like this?
image

**Comment by lpil** [comment]
ahah gosh that looks very silly. Yes perfect!

**Comment by okkdev** [comment]
This should be it :)

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
