### PR TITLE
mdbook version update and new guard clause docs

### PR DESCRIPTION
**Pull request by tomwhatmore**
Went for just a single example in the end as the float and int versions are very similar.

### CODE REVIEW

**Comment by lpil** [comment]
Could you update this PR to target the gleam-0.8 branch please? These features are not released yet

**Comment by tomwhatmore** [comment]
Is it not already?

**Comment by lpil** [comment]
They're on master but we have not released a new versin from master yet.

**Comment by lpil** [comment]
Ah yes! I got confused. Thank you :)

**Pull request merged**
