### PR TITLE
Add a link for Gleam Weekly

### PR DESCRIPTION
**Pull request by CrowdHailer**

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Thank you

**Review by lpil — COMMENTED** [review]
Oh, sorry. Could you put this on the community page instead

**Comment by CrowdHailer** [comment]
I think you mean alongside things here 
image
If so do you have a place you source the svg's from. I would suggest getting an email icon SVG?

Separately to that I think having it next to discord, whereever that might be i.e. here in the footer, makes sense because I think it always catches the people for whom discord is too high frequency. (I spotted a Gleam weekly link in the Gloogle footer which is what gave me the idea)

**Comment by lpil** [comment]
I'd probably add a section below them as it's not as important as either of those two forums

**Comment by CrowdHailer** [comment]
I'm not entirely sure how you would like this to be added here.

**Comment by CrowdHailer** [comment]
How does this look?

**Review by lpil — APPROVED** [review]
Sorry for the slow reply, thank you!

**Pull request merged**
