### PR TITLE
fix: code comments going out of bounds

### PR DESCRIPTION
**Pull request by LePichu**
Fixes `gleam.toml` code comments going out of bounds on Mobile displays.

Before: 
image

After:
image

### CODE REVIEW

**Comment by LePichu** [comment]
Better picture of issue: 
image

**Comment by LePichu** [comment]
> Thanks!
> 
> Could we actually put this in code blocks in general? There is a chance of long lines that are not comments in future too

It targets `.hljs-comment` as of now, but I can make it target `.code-comment` too.

**Comment by aslilac** [comment]
fwiw, the more common way I usually see this fixed is to make the code blocks horizontally scrolling

**Review by lpil — APPROVED** [review]
Thank you 💜

**Pull request merged**
